// src/games/flashcue/screens/FlashCueScreen/styles.ts
import { StyleSheet } from 'react-native';
import { scale, verticalScale, moderateScale } from '@/utils/responsive';
import { THEME } from '@/games/flashcue/constants';

export const styles = StyleSheet.create({
    // ============= IDLE STATE STYLES =============
    idleContainer: {
        flex: 1,
        backgroundColor: THEME.bg,
    },
    idleContent: {
        paddingHorizontal: scale(24),
        paddingTop: verticalScale(16),
        paddingBottom: verticalScale(48),
    },
    // Shared static header for all Flash Cue screens (idle / playing / finished)
    screenHeader: {
        paddingTop: verticalScale(48),
        paddingHorizontal: scale(24),
        paddingBottom: verticalScale(8),
    },
    backButton: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: verticalScale(24),
        gap: scale(6),
        alignSelf: 'flex-start',
        paddingVertical: verticalScale(4),
        paddingRight: scale(12),
    },
    backButtonText: {
        color: THEME.textMuted,
        fontSize: moderateScale(14),
        fontWeight: '600',
    },
    header: {
        alignItems: 'center',
        marginBottom: verticalScale(32),
    },
    iconContainer: {
        width: scale(72),
        height: scale(72),
        backgroundColor: THEME.accent + '15',
        borderRadius: moderateScale(24),
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: verticalScale(16),
        position: 'relative',
        borderWidth: 1,
        borderColor: THEME.accent + '30',
    },
    iconGlow: {
        position: 'absolute',
        width: scale(100),
        height: scale(100),
        backgroundColor: THEME.accent + '08',
        borderRadius: moderateScale(50),
    },
    title: {
        color: THEME.text,
        fontSize: moderateScale(32),
        fontWeight: '800',
        textAlign: 'center',
        letterSpacing: -0.5,
    },
    subtitleBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(6),
        backgroundColor: THEME.accent + '15',
        paddingHorizontal: scale(12),
        paddingVertical: verticalScale(6),
        borderRadius: moderateScale(20),
        marginTop: verticalScale(8),
    },
    subtitle: {
        color: THEME.accent,
        fontSize: moderateScale(12),
        fontWeight: '700',
        letterSpacing: 1,
        textTransform: 'uppercase',
    },
    quoteCard: {
        backgroundColor: THEME.surface,
        padding: scale(24),
        borderRadius: moderateScale(20),
        borderWidth: 1,
        borderColor: THEME.surfaceLight,
        marginBottom: verticalScale(28),
        position: 'relative',
        overflow: 'hidden',
    },
    quoteIconContainer: {
        position: 'absolute',
        top: scale(12),
        left: scale(16),
        opacity: 0.1,
    },
    quoteIcon: {
        fontSize: moderateScale(60),
        color: THEME.accent,
        fontWeight: 'bold',
    },
    quoteText: {
        color: THEME.textMuted,
        fontSize: moderateScale(15),
        lineHeight: moderateScale(24),
        fontStyle: 'italic',
        paddingTop: verticalScale(8),
    },
    quoteAuthorContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: verticalScale(16),
        gap: scale(12),
    },
    authorDivider: {
        width: scale(24),
        height: 2,
        backgroundColor: THEME.accent + '40',
        borderRadius: 1,
    },
    quoteAuthor: {
        color: THEME.textDim,
        fontSize: moderateScale(12),
        fontWeight: '600',
    },
    instructions: {
        marginBottom: verticalScale(8),
        gap: verticalScale(12),
    },
    instructionRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        backgroundColor: THEME.surface + '80',
        padding: scale(16),
        borderRadius: moderateScale(16),
        borderWidth: 1,
        borderColor: THEME.surfaceLight + '60',
    },
    stepNumber: {
        width: scale(28),
        height: scale(28),
        borderRadius: moderateScale(10),
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: scale(14),
    },
    instructionContent: {
        flex: 1,
        paddingTop: verticalScale(4),
    },
    instructionText: {
        color: THEME.textMuted,
        fontSize: moderateScale(14),
        lineHeight: moderateScale(22),
    },
    highlight: {
        color: THEME.text,
        fontWeight: '700',
    },
    highlightAccent: {
        color: THEME.accent,
        fontWeight: '700',
    },
    highlightError: {
        color: THEME.error,
        fontWeight: '700',
    },
    underline: {
        fontWeight: '700',
        textDecorationLine: 'underline',
        color: THEME.text,
    },
    startButton: {
        backgroundColor: THEME.accent,
        height: verticalScale(60),
        borderRadius: moderateScale(16),
        marginTop: verticalScale(24),
        shadowColor: THEME.accent,
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.35,
        shadowRadius: 16,
        elevation: 8,
    },
    startButtonInner: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: scale(10),
    },
    startButtonText: {
        color: 'white',
        fontSize: moderateScale(17),
        fontWeight: '700',
        letterSpacing: 0.3,
    },

    // ============= PLAYING STATE STYLES =============
    playingWrapper: {
        flex: 1,
        backgroundColor: THEME.bg,
    },
    playingHeader: {
        position: 'absolute',
        top: verticalScale(48),
        left: scale(24),
        right: scale(24),
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        zIndex: 2,
    },
    exitButton: {
        width: scale(32),
        height: scale(32),
        borderRadius: moderateScale(16),
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: THEME.surface,
        borderWidth: 1,
        borderColor: THEME.surfaceLight,
    },
    headerProgressContainer: {
        flex: 1,
        marginLeft: scale(12),
    },
    playingContainer: {
        flex: 1,
        backgroundColor: THEME.bg,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: scale(24),
    },
    progressTrack: {
        width: '100%',
        height: verticalScale(6),
        backgroundColor: THEME.surfaceLight,
        borderRadius: moderateScale(3),
        overflow: 'hidden',
        position: 'relative',
    },
    progressBar: {
        height: '100%',
        backgroundColor: THEME.accent,
        borderRadius: moderateScale(3),
    },
    progressText: {
        color: THEME.textDim,
        fontSize: moderateScale(12),
        fontWeight: '600',
        marginTop: verticalScale(8),
        letterSpacing: 0.5,
    },
    playingFooter: {
        position: 'absolute',
        bottom: verticalScale(48),
        alignItems: 'center',
    },
    footerPulse: {
        width: scale(8),
        height: scale(8),
        backgroundColor: THEME.accent + '60',
        borderRadius: scale(4),
        marginBottom: verticalScale(12),
    },
    footerText: {
        color: THEME.textDim,
        fontSize: moderateScale(13),
        fontWeight: '600',
        letterSpacing: 0.5,
        textAlign: 'center',
    },

    fixationRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        width: '100%',
        maxWidth: scale(260),
    },
    peripheralBox: {
        width: scale(72),
        height: scale(72),
        borderRadius: moderateScale(24),
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: THEME.surface,
        borderWidth: 1,
        borderColor: THEME.surfaceLight,
    },
    peripheralCueActive: {
        shadowColor: THEME.accent,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.6,
        shadowRadius: 18,
        borderColor: THEME.accent,
        backgroundColor: THEME.surfaceGlow,
    },
    peripheralX: {
        color: THEME.text,
        fontSize: moderateScale(40),
        fontWeight: '800',
    },
    fixationPlus: {
        color: THEME.textDim,
        fontSize: moderateScale(42),
        fontWeight: '400',
        textAlign: 'center',
        marginHorizontal: scale(24),
    },

    // ============= FINISHED STATE STYLES =============
    finishedContainer: {
        flex: 1,
        backgroundColor: THEME.bg,
    },
    finishedContent: {
        paddingHorizontal: scale(24),
        paddingVertical: verticalScale(48),
    },
    finishedHeader: {
        alignItems: 'center',
        marginBottom: verticalScale(36),
    },
    trophyContainer: {
        width: scale(72),
        height: scale(72),
        backgroundColor: THEME.surface,
        borderRadius: moderateScale(24),
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: verticalScale(16),
        borderWidth: 2,
    },
    finishedSubtitle: {
        color: THEME.textDim,
        fontSize: moderateScale(14),
        fontWeight: '600',
        textTransform: 'uppercase',
        letterSpacing: 2,
        marginBottom: verticalScale(4),
    },
    finishedTitle: {
        color: THEME.text,
        fontSize: moderateScale(32),
        fontWeight: '800',
        letterSpacing: -0.5,
    },
    performanceBadge: {
        paddingHorizontal: scale(16),
        paddingVertical: verticalScale(8),
        borderRadius: moderateScale(20),
        marginTop: verticalScale(12),
    },
    performanceText: {
        fontSize: moderateScale(14),
        fontWeight: '700',
        letterSpacing: 0.5,
    },
    resultsList: {
        marginBottom: verticalScale(32),
        gap: verticalScale(12),
    },
    resultCard: {
        backgroundColor: THEME.surface,
        borderWidth: 1,
        borderColor: THEME.surfaceLight,
        padding: scale(20),
        borderRadius: moderateScale(20),
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    resultInfo: {
        flex: 1,
    },
    resultLabel: {
        color: THEME.text,
        fontSize: moderateScale(15),
        fontWeight: '700',
        marginBottom: verticalScale(2),
    },
    resultSublabel: {
        color: THEME.textDim,
        fontSize: moderateScale(11),
        marginBottom: verticalScale(8),
    },
    resultValue: {
        color: THEME.accent,
        fontSize: moderateScale(28),
        fontWeight: '800',
        letterSpacing: -0.5,
    },
    resultIcon: {
        width: scale(52),
        height: scale(52),
        borderRadius: moderateScale(16),
        alignItems: 'center',
        justifyContent: 'center',
    },
    actionButtons: {
        gap: verticalScale(12),
    },
    retryButton: {
        backgroundColor: THEME.text,
        height: verticalScale(60),
        borderRadius: moderateScale(16),
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: scale(10),
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 12,
        elevation: 4,
    },
    retryButtonText: {
        color: THEME.bg,
        fontSize: moderateScale(17),
        fontWeight: '700',
        letterSpacing: 0.3,
    },
    homeButton: {
        height: verticalScale(52),
        borderRadius: moderateScale(16),
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: scale(8),
        backgroundColor: THEME.surface,
        borderWidth: 1,
        borderColor: THEME.surfaceLight,
    },
    homeButtonText: {
        color: THEME.textMuted,
        fontSize: moderateScale(15),
        fontWeight: '600',
    },
});


