// src/games/meditation/screens/MeditationScreen/styles.ts
import { StyleSheet } from 'react-native';
import { scale, verticalScale, moderateScale } from '@/utils/responsive';
import { THEME } from '@/games/meditation/constants';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: THEME.bg,
    },
    headerWrapper: {
        paddingTop: verticalScale(48),
        paddingHorizontal: scale(24),
        paddingBottom: verticalScale(8),
    },
    backButton: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: verticalScale(24),
        gap: scale(6),
        alignSelf: 'flex-start',
        paddingVertical: verticalScale(4),
        paddingRight: scale(12),
    },
    backButtonText: {
        color: THEME.textMuted,
        fontSize: moderateScale(14),
        fontWeight: '600',
    },
    idleContent: {
        paddingHorizontal: scale(24),
        paddingBottom: verticalScale(32),
    },
    title: {
        color: THEME.text,
        fontSize: moderateScale(30),
        fontWeight: '800',
        letterSpacing: -0.5,
        marginBottom: verticalScale(6),
    },
    subtitle: {
        color: THEME.textMuted,
        fontSize: moderateScale(14),
    },
    card: {
        backgroundColor: THEME.surface,
        borderRadius: moderateScale(20),
        padding: scale(20),
        borderWidth: 1,
        borderColor: '#1e293b',
        marginTop: verticalScale(24),
    },
    cardTitle: {
        color: THEME.text,
        fontSize: moderateScale(16),
        fontWeight: '700',
        marginBottom: verticalScale(4),
    },
    cardText: {
        color: THEME.textMuted,
        fontSize: moderateScale(14),
        lineHeight: moderateScale(22),
    },
    durationRow: {
        flexDirection: 'row',
        gap: scale(8),
        marginTop: verticalScale(16),
    },
    durationChip: {
        flex: 1,
        borderRadius: moderateScale(16),
        borderWidth: 1,
        borderColor: '#1e293b',
        paddingVertical: verticalScale(10),
        paddingHorizontal: scale(12),
        backgroundColor: THEME.surface,
    },
    durationChipActive: {
        borderColor: THEME.accent,
        backgroundColor: THEME.accentSoft,
    },
    durationChipLabel: {
        color: THEME.text,
        fontSize: moderateScale(13),
        fontWeight: '700',
    },
    durationChipSub: {
        color: THEME.textMuted,
        fontSize: moderateScale(11),
        marginTop: verticalScale(2),
    },
    customInputRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: verticalScale(16),
        gap: scale(8),
    },
    customLabel: {
        color: THEME.textMuted,
        fontSize: moderateScale(13),
    },
    customInput: {
        flex: 0,
        width: scale(70),
        height: verticalScale(40),
        borderRadius: moderateScale(12),
        borderWidth: 1,
        borderColor: '#1e293b',
        paddingHorizontal: scale(10),
        color: THEME.text,
        fontSize: moderateScale(14),
    },
    startButton: {
        marginTop: verticalScale(24),
        height: verticalScale(56),
        borderRadius: moderateScale(18),
        backgroundColor: THEME.accent,
        alignItems: 'center',
        justifyContent: 'center',
    },
    startButtonText: {
        color: THEME.text,
        fontSize: moderateScale(16),
        fontWeight: '700',
        letterSpacing: 0.4,
    },

    // Playing
    playingWrapper: {
        flex: 1,
        paddingHorizontal: scale(24),
        paddingBottom: verticalScale(32),
        justifyContent: 'space-between',
    },
    timerSection: {
        alignItems: 'center',
        marginTop: verticalScale(24),
    },
    timerLabel: {
        color: THEME.textMuted,
        fontSize: moderateScale(13),
        marginBottom: verticalScale(6),
    },
    timerText: {
        color: THEME.text,
        fontSize: moderateScale(40),
        fontWeight: '800',
        letterSpacing: 2,
    },
    orbWrapper: {
        marginTop: verticalScale(24),
        alignItems: 'center',
        justifyContent: 'center',
    },
    orbOuter: {
        width: scale(220),
        height: scale(220),
        borderRadius: scale(110),
        backgroundColor: THEME.accentSoft,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: THEME.accent,
        shadowOffset: { width: 0, height: 18 },
        shadowOpacity: 0.35,
        shadowRadius: 40,
        elevation: 18,
    },
    orbInner: {
        width: scale(150),
        height: scale(150),
        borderRadius: scale(75),
        backgroundColor: THEME.surfaceSoft,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: THEME.accentSoft,
        overflow: 'hidden',
    },
    orbGlow: {
        position: 'absolute',
        width: scale(260),
        height: scale(260),
        borderRadius: scale(130),
        backgroundColor: THEME.accentSoft,
    },
    orbSheen: {
        position: 'absolute',
        width: scale(140),
        height: scale(260),
        borderRadius: scale(130),
        backgroundColor: 'rgba(255,255,255,0.10)',
        transform: [{ rotate: '-35deg' }],
    },
    orbHint: {
        color: THEME.textMuted,
        fontSize: moderateScale(12),
        marginTop: verticalScale(10),
        textAlign: 'center',
    },
    musicRow: {
        marginTop: verticalScale(14),
        alignItems: 'center',
    },
    musicButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(8),
        paddingHorizontal: scale(16),
        paddingVertical: verticalScale(8),
        borderRadius: moderateScale(999),
        borderWidth: 1,
        borderColor: THEME.accentSoft,
        backgroundColor: '#020617',
    },
    musicButtonText: {
        color: THEME.text,
        fontSize: moderateScale(13),
        fontWeight: '600',
    },
    musicButtonSub: {
        color: THEME.textMuted,
        fontSize: moderateScale(11),
    },

    distractionHeader: {
        marginTop: verticalScale(24),
        marginBottom: verticalScale(8),
    },
    distractionTitle: {
        color: THEME.text,
        fontSize: moderateScale(14),
        fontWeight: '700',
    },
    distractionSubtitle: {
        color: THEME.textMuted,
        fontSize: moderateScale(12),
        marginTop: verticalScale(2),
    },
    distractionRow: {
        flexDirection: 'row',
        gap: scale(8),
        marginTop: verticalScale(8),
    },
    distractionChip: {
        flex: 1,
        borderRadius: moderateScale(16),
        borderWidth: 1,
        borderColor: '#1e293b',
        paddingVertical: verticalScale(10),
        paddingHorizontal: scale(12),
        backgroundColor: THEME.surface,
    },
    distractionLabel: {
        color: THEME.text,
        fontSize: moderateScale(13),
        fontWeight: '700',
    },
    distractionHint: {
        color: THEME.textMuted,
        fontSize: moderateScale(11),
        marginTop: verticalScale(2),
    },
    footerHint: {
        marginTop: verticalScale(12),
        color: THEME.textMuted,
        fontSize: moderateScale(11),
        textAlign: 'center',
    },

    // Finished
    finishedContent: {
        flex: 1,
        paddingHorizontal: scale(24),
        paddingBottom: verticalScale(32),
    },
    finishedTitle: {
        color: THEME.text,
        fontSize: moderateScale(24),
        fontWeight: '800',
        marginBottom: verticalScale(6),
    },
    finishedSubtitle: {
        color: THEME.textMuted,
        fontSize: moderateScale(14),
        marginBottom: verticalScale(16),
    },
    statRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingVertical: verticalScale(6),
    },
    statLabel: {
        color: THEME.textMuted,
        fontSize: moderateScale(13),
    },
    statValue: {
        color: THEME.text,
        fontSize: moderateScale(13),
        fontWeight: '600',
    },
    finishedButtonRow: {
        marginTop: verticalScale(24),
        flexDirection: 'row',
        gap: scale(10),
    },
    finishedButtonPrimary: {
        flex: 1,
        height: verticalScale(52),
        borderRadius: moderateScale(18),
        backgroundColor: THEME.accent,
        alignItems: 'center',
        justifyContent: 'center',
    },
    finishedButtonSecondary: {
        flex: 1,
        height: verticalScale(52),
        borderRadius: moderateScale(18),
        backgroundColor: '#111827',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: '#1f2937',
    },
    finishedButtonTextPrimary: {
        color: THEME.text,
        fontSize: moderateScale(15),
        fontWeight: '600',
    },
    finishedButtonTextSecondary: {
        color: THEME.textMuted,
        fontSize: moderateScale(15),
        fontWeight: '600',
    },
    noteOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(15,23,42,0.85)',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: scale(24),
    },
    noteCard: {
        width: '100%',
        borderRadius: moderateScale(24),
        backgroundColor: '#020617',
        padding: scale(20),
        borderWidth: 1,
        borderColor: '#1e293b',
    },
    noteTitle: {
        color: THEME.text,
        fontSize: moderateScale(16),
        fontWeight: '700',
        marginBottom: verticalScale(4),
    },
    noteSubtitle: {
        color: THEME.textMuted,
        fontSize: moderateScale(12),
        marginBottom: verticalScale(12),
    },
    noteInput: {
        minHeight: verticalScale(80),
        borderRadius: moderateScale(16),
        borderWidth: 1,
        borderColor: '#1e293b',
        paddingHorizontal: scale(12),
        paddingVertical: verticalScale(10),
        color: THEME.text,
        fontSize: moderateScale(14),
        textAlignVertical: 'top',
        marginBottom: verticalScale(16),
    },
    noteButtonsRow: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        gap: scale(10),
    },
    noteButtonSecondary: {
        paddingHorizontal: scale(14),
        paddingVertical: verticalScale(8),
        borderRadius: moderateScale(14),
        backgroundColor: '#020617',
        borderWidth: 1,
        borderColor: '#1e293b',
    },
    noteButtonPrimary: {
        paddingHorizontal: scale(14),
        paddingVertical: verticalScale(8),
        borderRadius: moderateScale(14),
        backgroundColor: THEME.accent,
    },
    noteButtonTextSecondary: {
        color: THEME.textMuted,
        fontSize: moderateScale(13),
        fontWeight: '600',
    },
    noteButtonTextPrimary: {
        color: THEME.text,
        fontSize: moderateScale(13),
        fontWeight: '600',
    },
});


