// assets/songs/index.ts
// Meditation background tracks
//
// IMPORTANT: Place your audio files in this `assets/songs` folder.
// Example: move "Lupe Fiasco - Paris, Tokyo (Instrumental) Extended.mp3"
// into this folder and keep the name "lupe-paris-tokyo-instrumental.mp3"
// or update the path below to match your actual filename.

export type MeditationTrack = {
    id: string;
    label: string;
    description: string;
    // React Native asset reference returned by require()
    source?: any;
    // Optional base pulse duration (ms) for syncing animations to the track's feel
    pulseDurationMs?: number;
    // Optional per-segment pulse durations (ms) generated by analysis script
    pulsesMs?: number[];
};

// Update the require() path if you keep a different name for the file.
// If the file is not present yet, the extra track option will be hidden.
let track01Source: any | undefined;
let track01Meta: any | undefined;
try {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    track01Source = require('./lupe-paris-tokyo-instrumental.mp3');
} catch {
    track01Source = undefined;
}

try {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    track01Meta = require('./track-01.meta.json');
} catch {
    track01Meta = undefined;
}

export const MEDITATION_TRACKS: MeditationTrack[] = [
    {
        id: 'silence',
        label: 'Silence',
        description: 'No background audio',
    },
    ...(track01Source
        ? ([
              {
                  id: track01Meta?.id ?? 'track-01',
                  label: track01Meta?.label ?? 'Tokyo, Paris',
                  description: track01Meta?.description ?? 'Warm lo-fi waves for background focus',
                  source: track01Source,
                  pulseDurationMs: track01Meta?.pulseDurationMs ?? 4200,
                  pulsesMs: Array.isArray(track01Meta?.pulsesMs)
                      ? (track01Meta?.pulsesMs as number[])
                      : undefined,
              },
          ] as MeditationTrack[])
        : []),
];


